version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - exitAfterDefer
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: false
    funlen:
      lines: 170
      statements: 80
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 5
    lll:
      line-length: 140
    misspell:
      locale: US
    nestif:
      min-complexity: 5
    nolintlint:
      require-explanation: true
      require-specific: true
    gosec:
      excludes:
        - G104
    revive:
      severity: warning
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
        - name: modifies-value-receiver
        - name: waitgroup-by-value
        - name: atomic
        - name: range-val-in-closure
        - name: range-val-address
        - name: constant-logical-expr
        - name: identical-branches
        - name: unconditional-recursion
        - name: duplicated-imports
        - name: unhandled-error
          arguments:
            - "fmt.Printf"
            - "fmt.Println"
            - "fmt.Print"
    depguard:
      rules:
        main:
          deny:
            - pkg: "io/ioutil"
              desc: "Deprecated: use io and os packages instead"
            - pkg: "github.com/pkg/errors"
              desc: "Use fmt.Errorf with %w instead"
    govet:
      disable:
        - fieldalignment
      enable-all: true
  exclusions:
    rules:
      # Relax rules for test files
      - linters:
          - dupl
          - funlen
          - goconst
          - gocyclo
          - gosec
          - errcheck
          - errorlint
          - gocritic
          - revive
          - dogsled
          - staticcheck
          - nestif
        path: _test\.go
      # Tool registration follows intentional repetitive pattern
      - linters:
          - dupl
        path: pkg/tools/
      # Write methods follow intentional read-modify-write pattern
      - linters:
          - dupl
        path: pkg/client/write\.go
      # Package name is intentional
      - linters:
          - revive
        path: pkg/types/
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/txn2/mcp-datahub
