# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: mcp-datahub

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go mod verify

builds:
  - id: mcp-datahub
    main: ./cmd/mcp-datahub
    binary: mcp-datahub
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -a
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Sign release artifacts with Cosign (keyless - uses OIDC identity)
signs:
  - id: archives
    cmd: cosign
    artifacts: archive
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--yes"
      - "--bundle=${signature}"
      - "${artifact}"
  - id: checksums
    cmd: cosign
    artifacts: checksum
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--yes"
      - "--bundle=${signature}"
      - "${artifact}"

# Generate Software Bill of Materials for archives
sboms:
  - artifacts: archive

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^feat'
      order: 0
    - title: Bug Fixes
      regexp: '^fix'
      order: 1
    - title: Security
      regexp: '^security'
      order: 2
    - title: Others
      order: 999

# Docker Images - Using v2 format with multi-platform support
dockers_v2:
  - id: alpine
    dockerfile: Dockerfile
    ids:
      - mcp-datahub
    images:
      - ghcr.io/txn2/mcp-datahub
    tags:
      - latest
      - "{{ .Tag }}"
      - "v{{ .Major }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "{{ .GitURL }}"
      org.opencontainers.image.description: "MCP server for DataHub data catalogs"
      org.opencontainers.image.licenses: "Apache-2.0"

# Sign Docker images with Cosign (keyless)
docker_signs:
  - cmd: cosign
    args:
      - "sign"
      - "--yes"
      - "${artifact}"
    artifacts: all

nfpms:
  - id: default
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage: https://github.com/txn2/mcp-datahub
    description: MCP server for DataHub data catalogs
    maintainer: Craig Johnston <cj@imti.co>
    license: Apache 2.0
    vendor: txn2
    formats: [apk, deb, rpm]

brews:
  - name: mcp-datahub
    repository:
      owner: txn2
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/txn2/mcp-datahub
    description: MCP server for DataHub data catalogs
    license: Apache-2.0
    install: |
      bin.install "mcp-datahub"
    test: |
      system "#{bin}/mcp-datahub", "--version"

release:
  github:
    owner: txn2
    name: mcp-datahub
  name_template: "{{.ProjectName}}-v{{.Version}}"
  prerelease: auto
  mode: append
  footer: |
    ## Installation

    ### Claude Desktop (macOS/Windows)
    Download the `.mcpb` bundle for your platform and double-click to install:
    - **macOS Apple Silicon (M1/M2/M3/M4)**: `mcp-datahub_{{ .Version }}_darwin_arm64.mcpb`
    - **macOS Intel**: `mcp-datahub_{{ .Version }}_darwin_amd64.mcpb`
    - **Windows**: `mcp-datahub_{{ .Version }}_windows_amd64.mcpb`

    ### Homebrew (macOS)
    ```bash
    brew install txn2/tap/mcp-datahub
    ```

    ### Claude Code CLI
    ```bash
    claude mcp add datahub \
      -e DATAHUB_URL=https://your-datahub.example.com/api/graphql \
      -e DATAHUB_TOKEN=your-token \
      -- mcp-datahub
    ```

    ### Docker
    ```bash
    docker pull ghcr.io/txn2/mcp-datahub:{{ .Tag }}
    ```

    ## Verification

    All release artifacts are signed with Cosign. Verify with:
    ```bash
    cosign verify-blob --bundle mcp-datahub_{{ .Version }}_linux_amd64.tar.gz.sigstore.json \
      mcp-datahub_{{ .Version }}_linux_amd64.tar.gz
    ```
